"""Shared compose-override generation for services published through gluetun."""

from __future__ import annotations

from pathlib import Path

from stremioguard.comet_gateway import COMET_GATEWAY_CONTAINER_PORT, CometGatewayConfig
from stremioguard.config import CometConfig
from stremioguard.env import atomic_write_text

# Gluetun v3.40+ requires control-server auth for every route. This managed
# role file re-opens only the read-only public-IP route the watchdog polls,
# and the control server listens on 127.0.0.1 inside gluetun's namespace only.
# It lives in user-owned .stremio/ (gluetun-data/ is root-owned) and is
# mounted to /gluetun/auth/config.toml through the generated override.
GLUETUN_AUTH_CONTAINER_PATH = "/gluetun/auth/config.toml"
GLUETUN_AUTH_TEMPLATE = """\
# Generated by ./stremio; do not edit by hand.
# Grants unauthenticated access to the read-only public IP route so the
# watchdog can poll gluetun's own egress view instead of external services.
[[roles]]
name = "stremioguard"
routes = ["GET /v1/publicip/ip"]
auth = "none"
"""


def ensure_gluetun_auth_config(root_dir: Path) -> Path:
    """Write the managed control-server role file, honoring user overrides."""
    path = root_dir / ".stremio" / "gluetun-auth.toml"
    if path.exists():
        content = path.read_text(encoding="utf-8")
        if "Generated by ./stremio" not in content:
            return path
        if content == GLUETUN_AUTH_TEMPLATE:
            return path
    atomic_write_text(path, GLUETUN_AUTH_TEMPLATE, mode=0o644)
    return path


def render_gluetun_ports(
    bind_addresses: list[str],
    port_mappings: list[tuple[int, int]],
    extra_lines: list[str] | None = None,
) -> str | None:
    if not bind_addresses and not extra_lines:
        return None
    lines: list[str] = []
    for address in bind_addresses:
        for host_port, container_port in port_mappings:
            lines.append(f'      - "{address}:{host_port}:{container_port}"')
    lines.extend(extra_lines or [])
    if not lines:
        return None
    return "\n".join(lines)


def render_stack_compose_override(
    *,
    bind_addresses: list[str],
    stremio_host_port: int,
    stremio_container_port: int,
    stremio_enabled: bool,
    comet_config: CometConfig | None,
    comet_gateway_config: CometGatewayConfig | None = None,
    gluetun_auth_config_file: Path | None = None,
) -> str:
    port_mappings: list[tuple[int, int]] = []
    if stremio_enabled:
        port_mappings.append((stremio_host_port, stremio_container_port))
    comet_gateway_enabled = bool(comet_gateway_config and comet_gateway_config.enabled)

    extra_gluetun_ports = []
    if comet_config and comet_config.enabled:
        if comet_gateway_enabled:
            extra_gluetun_ports.append(f'      - "127.0.0.1:{comet_config.host_port}:8000"')
            assert comet_gateway_config is not None
            for address in bind_addresses:
                extra_gluetun_ports.append(
                    f'      - "{address}:{comet_gateway_config.host_port}:'
                    f'{COMET_GATEWAY_CONTAINER_PORT}"'
                )
        else:
            for address in bind_addresses:
                extra_gluetun_ports.append(f'      - "{address}:{comet_config.host_port}:8000"')

    ports = render_gluetun_ports(bind_addresses, port_mappings, extra_gluetun_ports)
    content = ["# Generated by ./stremio; do not edit by hand.", "services:", "  gluetun:"]
    if gluetun_auth_config_file is not None:
        content.extend(
            [
                "    volumes:",
                f"      - {gluetun_auth_config_file}:{GLUETUN_AUTH_CONTAINER_PATH}:ro",
            ]
        )
    if ports is None:
        content.append("    ports: []")
    else:
        content.extend(["    ports:", ports])

    if comet_gateway_enabled and comet_gateway_config:
        content.extend(
            [
                "  comet-gateway:",
                "    volumes:",
                f"      - {comet_gateway_config.nginx_conf_file}:/etc/nginx/nginx.conf:ro",
                f"      - {comet_gateway_config.tokens_map_file}:/etc/nginx/tokens.map:ro",
            ]
        )

    if comet_config and comet_config.enabled:
        comet_volumes = [f"      - {comet_config.data_dir}:/app/data"]
        if comet_config.result_format_style != "emoji":
            comet_volumes.append(
                "      - "
                f"{comet_config.state_dir / 'formatting.py'}:/app/comet/utils/formatting.py:ro"
            )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'stream.py'}:/app/comet/api/endpoints/stream.py:ro"
        )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'config.py'}:/app/comet/api/endpoints/config.py:ro"
        )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'index.html'}:/app/comet/templates/index.html:ro"
        )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'torrentio.py'}:/app/comet/scrapers/torrentio.py:ro"
        )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'filtering.py'}:/app/comet/services/filtering.py:ro"
        )
        if comet_config.patch_episode_pack_results:
            orch_src = comet_config.state_dir / "orchestration.py"
            comet_volumes.append(f"      - {orch_src}:/app/comet/services/orchestration.py:ro")
        metadata_src = comet_config.state_dir / "metadata_service.py"
        if metadata_src.exists():
            comet_volumes.append(f"      - {metadata_src}:/app/comet/metadata_service.py:ro")
        content.extend(
            [
                "  comet:",
                f"    image: {comet_config.image}",
                "    env_file:",
                f"      - {comet_config.runtime_env_file}",
                "    volumes:",
                *comet_volumes,
                "    healthcheck:",
                f"      interval: {comet_config.healthcheck_interval_seconds}s",
                "      timeout: 5s",
                "      retries: 5",
                "      start_period: 10s",
                "  comet-postgres:",
                "    env_file:",
                f"      - {comet_config.state_dir / 'postgres.env'}",
                "    volumes:",
                f"      - {comet_config.postgres_data_dir}:/var/lib/postgresql/",
            ]
        )

    return "\n".join(content) + "\n"
