"""Shared compose-override generation for services published through gluetun."""

from __future__ import annotations

from stremioguard.comet_gateway import COMET_GATEWAY_CONTAINER_PORT, CometGatewayConfig
from stremioguard.config import CometConfig


def render_gluetun_ports(
    bind_addresses: list[str],
    port_mappings: list[tuple[int, int]],
    extra_lines: list[str] | None = None,
) -> str | None:
    if not bind_addresses and not extra_lines:
        return None
    lines: list[str] = []
    for address in bind_addresses:
        for host_port, container_port in port_mappings:
            lines.append(f'      - "{address}:{host_port}:{container_port}"')
    lines.extend(extra_lines or [])
    if not lines:
        return None
    return "\n".join(lines)


def render_stack_compose_override(
    *,
    bind_addresses: list[str],
    stremio_host_port: int,
    stremio_container_port: int,
    stremio_enabled: bool,
    comet_config: CometConfig | None,
    comet_gateway_config: CometGatewayConfig | None = None,
) -> str:
    port_mappings: list[tuple[int, int]] = []
    if stremio_enabled:
        port_mappings.append((stremio_host_port, stremio_container_port))
    comet_gateway_enabled = bool(comet_gateway_config and comet_gateway_config.enabled)

    extra_gluetun_ports = []
    if comet_config and comet_config.enabled:
        if comet_gateway_enabled:
            extra_gluetun_ports.append(f'      - "127.0.0.1:{comet_config.host_port}:8000"')
            assert comet_gateway_config is not None
            for address in bind_addresses:
                extra_gluetun_ports.append(
                    f'      - "{address}:{comet_gateway_config.host_port}:'
                    f'{COMET_GATEWAY_CONTAINER_PORT}"'
                )
        else:
            for address in bind_addresses:
                extra_gluetun_ports.append(f'      - "{address}:{comet_config.host_port}:8000"')

    ports = render_gluetun_ports(bind_addresses, port_mappings, extra_gluetun_ports)
    content = ["# Generated by ./stremio; do not edit by hand.", "services:", "  gluetun:"]
    if ports is None:
        content.append("    ports: []")
    else:
        content.extend(["    ports:", ports])

    if comet_gateway_enabled and comet_gateway_config:
        content.extend(
            [
                "  comet-gateway:",
                "    volumes:",
                f"      - {comet_gateway_config.nginx_conf_file}:/etc/nginx/nginx.conf:ro",
                f"      - {comet_gateway_config.tokens_map_file}:/etc/nginx/tokens.map:ro",
            ]
        )

    if comet_config and comet_config.enabled:
        comet_volumes = [f"      - {comet_config.data_dir}:/app/data"]
        if comet_config.result_format_style != "emoji":
            comet_volumes.append(
                "      - "
                f"{comet_config.state_dir / 'formatting.py'}:/app/comet/utils/formatting.py:ro"
            )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'stream.py'}:/app/comet/api/endpoints/stream.py:ro"
        )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'config.py'}:/app/comet/api/endpoints/config.py:ro"
        )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'index.html'}:/app/comet/templates/index.html:ro"
        )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'torrentio.py'}:/app/comet/scrapers/torrentio.py:ro"
        )
        comet_volumes.append(
            f"      - {comet_config.state_dir / 'filtering.py'}:/app/comet/services/filtering.py:ro"
        )
        if comet_config.patch_episode_pack_results:
            orch_src = comet_config.state_dir / "orchestration.py"
            comet_volumes.append(f"      - {orch_src}:/app/comet/services/orchestration.py:ro")
        content.extend(
            [
                "  comet:",
                "    env_file:",
                f"      - {comet_config.runtime_env_file}",
                "    volumes:",
                *comet_volumes,
                "    healthcheck:",
                f"      interval: {comet_config.healthcheck_interval_seconds}s",
                "      timeout: 5s",
                "      retries: 5",
                "      start_period: 10s",
                "  comet-postgres:",
                "    volumes:",
                f"      - {comet_config.postgres_data_dir}:/var/lib/postgresql/",
            ]
        )

    return "\n".join(content) + "\n"
