"""Regression tests for compose-override rendering across different profiles."""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from stremioguard.publishing import (
    StackPublisher,
    ensure_gluetun_auth_config,
    render_stack_compose_override,
)

from .conftest import (
    FakeRunner,
    make_comet_config,
    make_comet_gateway_config,
    make_config,
)


class TestPublishingOverride(unittest.TestCase):
    def test_unified_profile_publishing(self) -> None:
        comet_cfg = make_comet_config(Path("/tmp"), enabled=True)
        gateway_cfg = make_comet_gateway_config(Path("/tmp"), enabled=True)
        content = render_stack_compose_override(
            bind_addresses=["10.0.0.1"],
            stremio_host_port=11470,
            stremio_container_port=11470,
            stremio_enabled=True,
            comet_config=comet_cfg,
            comet_gateway_config=gateway_cfg,
        )
        # Check both Stremio and Comet Gateway ports are published
        self.assertIn('"10.0.0.1:11470:11470"', content)
        self.assertIn('"10.0.0.1:18001:8090"', content)
        # Check raw Comet is localhost-only
        self.assertIn('"127.0.0.1:18000:8000"', content)
        self.assertIn("comet:", content)
        self.assertIn("comet-gateway:", content)

    def test_stremio_only_profile_publishing(self) -> None:
        content = render_stack_compose_override(
            bind_addresses=["10.0.0.1"],
            stremio_host_port=11470,
            stremio_container_port=11470,
            stremio_enabled=True,
            comet_config=None,
            comet_gateway_config=None,
        )
        self.assertIn('"10.0.0.1:11470:11470"', content)
        self.assertNotIn("comet:", content)
        self.assertNotIn("comet-gateway:", content)
        self.assertNotIn("18001", content)
        self.assertNotIn("18000", content)

    def test_comet_only_profile_publishing(self) -> None:
        comet_cfg = make_comet_config(Path("/tmp"), enabled=True)
        gateway_cfg = make_comet_gateway_config(Path("/tmp"), enabled=True)
        content = render_stack_compose_override(
            bind_addresses=["10.0.0.1"],
            stremio_host_port=11470,
            stremio_container_port=11470,
            stremio_enabled=False,
            comet_config=comet_cfg,
            comet_gateway_config=gateway_cfg,
        )
        self.assertNotIn('"10.0.0.1:11470:11470"', content)
        self.assertIn('"10.0.0.1:18001:8090"', content)
        self.assertIn('"127.0.0.1:18000:8000"', content)
        self.assertIn("comet:", content)
        self.assertIn("comet-gateway:", content)


class TestGluetunAuthConfig(unittest.TestCase):
    def test_ensure_writes_managed_role_file(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = ensure_gluetun_auth_config(root)
            content = path.read_text(encoding="utf-8")
            self.assertEqual(path, root / ".stremio" / "gluetun-auth.toml")
            self.assertIn("[[roles]]", content)
            self.assertIn('routes = ["GET /v1/publicip/ip"]', content)
            self.assertIn('auth = "none"', content)

    def test_ensure_preserves_user_managed_file(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / ".stremio" / "gluetun-auth.toml"
            path.parent.mkdir(parents=True)
            custom = '[[roles]]\nname = "mine"\nauth = "basic"\n'
            path.write_text(custom, encoding="utf-8")
            ensure_gluetun_auth_config(root)
            self.assertEqual(path.read_text(encoding="utf-8"), custom)

    def test_ensure_refreshes_drifted_managed_file(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            path = root / ".stremio" / "gluetun-auth.toml"
            path.parent.mkdir(parents=True)
            path.write_text("# Generated by ./stremio; old contents\n", encoding="utf-8")
            ensure_gluetun_auth_config(root)
            self.assertIn('routes = ["GET /v1/publicip/ip"]', path.read_text(encoding="utf-8"))

    def test_override_mounts_auth_config_into_gluetun(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            auth_file = ensure_gluetun_auth_config(root)
            content = render_stack_compose_override(
                bind_addresses=["10.0.0.1"],
                stremio_host_port=11470,
                stremio_container_port=11470,
                stremio_enabled=True,
                comet_config=None,
                gluetun_auth_config_file=auth_file,
            )
            self.assertIn(f"- {auth_file}:/gluetun/auth/config.toml:ro", content)


class TestStackPublisher(unittest.TestCase):
    def test_stack_publisher_produces_identical_output(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            # Write a dummy .env
            env_path = root / ".env"
            env_path.write_text(
                "STREMIO_BIND_ADDRS=10.0.0.1\nSTREMIO_ENABLED=1\nSTREMIO_HOST_PORT=11470\nSTREMIO_CONTAINER_PORT=11470\n",
                encoding="utf-8",
            )

            # Run publisher
            pub = StackPublisher(root)
            # Mock CometConfig and CometGatewayConfig to be disabled
            comet_cfg = make_comet_config(root, enabled=False)
            gateway_cfg = make_comet_gateway_config(root, enabled=False)

            with (
                mock.patch("stremioguard.publishing.CometConfig.from_env", return_value=comet_cfg),
                mock.patch(
                    "stremioguard.publishing.CometGatewayConfig.from_env", return_value=gateway_cfg
                ),
            ):
                pub.publish()

            override_content = pub.compose_override_file.read_text(encoding="utf-8")

            # Direct rendering
            auth_file = ensure_gluetun_auth_config(root)
            direct_content = render_stack_compose_override(
                bind_addresses=["10.0.0.1"],
                stremio_host_port=11470,
                stremio_container_port=11470,
                stremio_enabled=True,
                comet_config=None,
                comet_gateway_config=None,
                gluetun_auth_config_file=auth_file,
            )
            self.assertEqual(override_content, direct_content)

    def test_compose_read_only_versus_fresh_mtime(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            # Write a dummy .env
            env_path = root / ".env"
            env_path.write_text(
                "STREMIO_BIND_ADDRS=127.0.0.1\nSTREMIO_ENABLED=1\n", encoding="utf-8"
            )

            from unittest import mock

            from stremioguard.guard import GluetunGuard

            runner = FakeRunner({})

            # Create a mock config
            cfg = make_config(root)
            guard = GluetunGuard(cfg, runner)

            # Generate the first compose override
            guard.write_compose_override()
            mtime_before = guard.config.compose_override_file.stat().st_mtime

            # 1. Calling read-only compose does NOT rewrite the override file
            # (publish is not called)
            with mock.patch("stremioguard.publishing.StackPublisher.publish") as publish_mock:
                guard.compose("ps", check=False)
                publish_mock.assert_not_called()
            self.assertEqual(guard.config.compose_override_file.stat().st_mtime, mtime_before)

            # 2. Calling compose_fresh DOES call StackPublisher.publish
            with mock.patch("stremioguard.publishing.StackPublisher.publish") as publish_mock:
                guard.compose_fresh("up", "-d", check=False)
                publish_mock.assert_called_once()


class TestPublisherFailClosed(unittest.TestCase):
    def _env(self, root: Path, *, gateway: bool) -> None:
        (root / ".env").write_text(
            f"COMET_ENABLED=1\nCOMET_GATEWAY_ENABLED={'1' if gateway else '0'}\n",
            encoding="utf-8",
        )

    def test_publish_raises_when_comet_enabled_but_manifest_missing(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._env(root, gateway=False)
            with self.assertRaisesRegex(RuntimeError, "no override bundle manifest"):
                StackPublisher(root).publish()

    def test_publish_raises_when_gateway_requires_missing_patch(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._env(root, gateway=True)
            state_dir = root / ".stremio" / "comet"
            state_dir.mkdir(parents=True)
            # Manifest lacking the gateway-required stream/config/template outputs.
            (state_dir / "bundle-manifest.json").write_text(
                json.dumps({"outputs": {"torrentio.py": "/app/comet/scrapers/torrentio.py"}}),
                encoding="utf-8",
            )
            with self.assertRaisesRegex(RuntimeError, "required by this deployment shape"):
                StackPublisher(root).publish()

    def test_publish_accepts_manifest_with_required_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._env(root, gateway=True)
            state_dir = root / ".stremio" / "comet"
            state_dir.mkdir(parents=True)
            outputs = {
                "stream.py": "/app/comet/api/endpoints/stream.py",
                "config.py": "/app/comet/api/endpoints/config.py",
                "index.html": "/app/comet/templates/index.html",
            }
            (state_dir / "bundle-manifest.json").write_text(
                json.dumps({"outputs": outputs}), encoding="utf-8"
            )
            StackPublisher(root).publish()
            content = (root / ".stremio" / "docker-compose.bindings.yml").read_text(
                encoding="utf-8"
            )
            for output_name, container_path in outputs.items():
                self.assertIn(f"{state_dir / output_name}:{container_path}:ro", content)

    def test_publish_skips_manifest_check_when_comet_disabled(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / ".env").write_text("COMET_ENABLED=0\n", encoding="utf-8")
            StackPublisher(root).publish()
            self.assertTrue((root / ".stremio" / "docker-compose.bindings.yml").exists())
